Slideshow view
<?php
/**
 * This page validate at w3c except for the two dojo types below
 * Joey will address this when this file moves from declarative dojo usage to programmatic
 * If you modifiy this file IT MUST BE VALIDATED before you close this file!!!
 *
 */
    $this->headLink()->appendStylesheet('/js-src/dojox/image/resources/Lightbox.css', 'screen, print');
?>
<div id="imageHolder">
<?php
$i = 0;
if(isset($this->data->paginator)) {

	if(count($this->data->paginator) >= 1) { ?>

		<?php foreach($this->data->paginator as $file) { ?>

		  <a href="<?php echo $this->data->albumPath . '/' . $file->fileName; ?>" data-dojo-type="dojox.image.Lightbox" data-dojo-props="group:'<?php echo $this->data->albumName; ?>',title:'<?php echo ($file->title != null) ? $file->title : $file->fileName; ?>',href:'<?php echo ($i === 0) ? $this->data->albumPath . '/' . $file->fileName : '' ;?>'">
		      <img src="<?php echo $this->data->albumPath . '/' . $file->fileName; ?>" alt="<?php echo ($file->alt != null) ? $file->alt : $file->fileName; ?>" />
		  </a>

  <?php } ?>
		<?php echo $this->paginationControl($this->data->paginator,'Sliding','pagination_control_slideshow_fileview.phtml', array('albumName' => $this->data->albumName, 'action' => $this->data->action)); ?>
<?php
	}
}
?>
</div>
<?php $this->headStyle()->captureStart(); ?>
#imageHolder {
width:800px;
margin: 0 auto 0 auto;
}
#imageHolder img {
width:200px;
margin: 0 25px 0 25px;
border: 0 none;
}
#imageHolder a {
outline: none;
}
#imageHolder a:link, #imageHolder a:visited, #imageHolder a:hover {
text-decoration: none;
}
<?php $this->headStyle()->captureEnd(); ?>