Slideshow view
<?php 
    $this->headLink()->appendStylesheet('/js-src/dojox/image/resources/Lightbox.css', 'screen, print');
    //$this->headLink()->appendStylesheet('/js-src/dojox/image/resources/Gallery.css', 'screen, print');
    //$this->headLink()->appendStylesheet('/js-src/dojox/image/resources/ThumbnailPicker.css', 'screen, print');
?>
<div id="imageHolder">
<?php 
$i = 0;
if(isset($this->data->paginator)) { 

	if(count($this->data->paginator) >= 1) { ?>
		
		<?php foreach($this->data->paginator as $file) { ?>
		
		  <a href="<?php echo $this->data->albumPath . '/' . $file->fileName; ?>" data-dojo-type="dojox.image.Lightbox" data-dojo-props="group:'<?php echo $this->data->albumName; ?>',title:'<?php echo $this->data->albumName; ?>',href:'<?php echo ($i === 0) ? $this->data->albumPath . '/' . $file->fileName : '' ;?>'">
		      <img src="<?php echo $this->data->albumPath . '/' . $file->fileName; ?>" alt="<?php echo $this->data->albumName; ?>" />
		  </a>

  <?php } ?>
		
<?php 
	}

}
?>
</div>
<?php $this->headStyle()->captureStart(); ?>
#imageHolder img {
width:200px;
}
<?php $this->headStyle()->captureEnd(); ?>
