<div id="user-register-content">
	<h2>Register</h2>
	<div id="user-register-form">	
<?php 
if(isset($this->messages) || isset($this->message)) {
	
	if(is_array($this->messages)) {
		
		echo '<span>', implode($this->messages) ,'</span>';
		
	} else {
		echo $this->message;
	}
}
?>
<?php 
if(isset($this->form)) {
	echo $this->form; 
}
?>
	</div>
</div>


<?php $this->headStyle()->captureStart(); ?>


<?php $this->headStyle()->captureEnd(); ?>
